In [130]:
import cloudscraper
import time
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
condo_name = []
condo_listing = []

bungalow_name = []
bungalow_listing = []

semi_detached_name = []
semi_detached_listing = []

terrace_name = []
terrace_listing = []

In [146]:
property_type = {
    "condo" : "property_type=N",
    "bungalow" : "property_type=B",
    "semi-detached" : "property_type=S",
    "terrace" : "property_type=T"
}


def BSPrep(URL):
    exitcode = 1
    while exitcode == 1:
        try:
            trial = 0
            while trial < 10:
                scraper = cloudscraper.create_scraper()
                print('Loading '+URL)
                s = scraper.get(URL)
                soup = BeautifulSoup(s.content, 'html.parser')
                if "captcha" in soup.text:
                    trial += 1
                    print('Retrying '+' ('+str(trial)+'/10) ...')
                    time.sleep(0.1)
                    continue
                elif "No Results" in soup.text:
                    print('Invalid URL, skipping '+URL)
                    trial = 99
                else:
                    trial = 99
            if trial == 10:
                print('Trial exceeded, skipping '+URL)
            exitcode = 0
            return soup
        except:
                print('Connection reset, retrying in 1 mins...', flush=True)
                time.sleep(60)
                

## Get the listing link
def find_name_url(soup, array_name, array_listing):
    for a in soup.find_all('a', {"class": "nav-link"}):
        if "#contact-agent" not in a["href"]:
            array_name.append(a["title"])
            array_listing.append(a["href"])
            

## Get the data and push to defined list
def request_and_pust(property_input, array_name_input, array_listing_input):
    property_type = property_input
    property_name = array_name_input
    property_listing = array_listing_input
    
    for i in range(1,100):
        print(i, "==")
        soup = BSPrep(f"https://www.propertyguru.com.my/property-for-sale/{i}?freetext=Penang&{property_type}&region_code=MY07")
        find_name_url(soup, property_name, property_listing)

In [ ]:
## Condominium
request_and_pust(property_type["condo"], condo_name, condo_listing)

In [ ]:
## Bungalow
request_and_pust(property_type["bungalow"], bungalow_name, bungalow_listing)

In [ ]:
## Semi Detached
request_and_pust(property_type["semi-detached"], semi_detached_name, semi_detached_listing)

In [ ]:
## Terrace
request_and_pust(property_type["terrace"], terrace_name, terrace_listing)

In [148]:
condo_df = pd.DataFrame(data={"property_name" : condo_name, "property_listing": condo_listing})

condo_df["property_type"] = "condominium"

condo_df.head()

,property_name,property_listing,property_type
0,For Sale - Tropicana Bay Residences,https://www.propertyguru.com.my/property-listi...,condominium
1,For Sale - Tropicana Bay Residences,https://www.propertyguru.com.my/property-listi...,condominium
2,For Sale - Tropicana Bay Residences,https://www.propertyguru.com.my/property-listi...,condominium
3,For Sale - Tropicana Bay Residences,https://www.propertyguru.com.my/property-listi...,condominium
4,For Sale - Middleton @ Minden Heights,https://www.propertyguru.com.my/property-listi...,condominium

In [150]:
bungalow_df = pd.DataFrame(data={"property_name" : bungalow_name, "property_listing": bungalow_listing})

bungalow_df["property_type"] = "bungalow"

bungalow_df.head()

,property_name,property_listing,property_type
0,For Sale - STRAITS QUAY - SEAVIEW BUNGALOW,https://www.propertyguru.com.my/property-listi...,bungalow
1,For Sale - Ferringhi villa,https://www.propertyguru.com.my/property-listi...,bungalow
2,For Sale - Bungalow in Pulau Tikus,https://www.propertyguru.com.my/property-listi...,bungalow
3,For Sale - Lintang Selayang Indah,https://www.propertyguru.com.my/property-listi...,bungalow
4,For Sale - Sino-Malay Palladian Heritage Bunga...,https://www.propertyguru.com.my/property-listi...,bungalow

In [157]:
semi_detached_df = pd.DataFrame(data={"property_name" : semi_detached_name, "property_listing": semi_detached_listing})

semi_detached_df["property_type"] = "semi_detached"

semi_detached_df.head()

,property_name,property_listing,property_type
0,For Sale - Hijauan Valdor,https://www.propertyguru.com.my/property-listi...,semi_detached
1,For Sale - Hijauan Valdor,https://www.propertyguru.com.my/property-listi...,semi_detached
2,For Sale - Semi D in Georgetown nr Padang Polo,https://www.propertyguru.com.my/property-listi...,semi_detached
3,For Sale - 2 Storey Semi D Residency Merbok,https://www.propertyguru.com.my/property-listi...,semi_detached
4,For Sale - Bandar Tasek Mutiara,https://www.propertyguru.com.my/property-listi...,semi_detached

In [158]:
semi_detached_df.to_csv("test.csv", index=False)

In [160]:
terrace_df = pd.DataFrame(data={"property_name" : terrace_name, "property_listing": terrace_listing})

terrace_df["property_type"] = "terrace"

terrace_df.head()

,property_name,property_listing,property_type
0,For Sale - Panchor Santuary Garden @ Nibong Tebal,https://www.propertyguru.com.my/property-listi...,terrace
1,For Sale - Sungai Ara,https://www.propertyguru.com.my/property-listi...,terrace
2,For Sale - Below Market Value Double Storey Ta...,https://www.propertyguru.com.my/property-listi...,terrace
3,For Sale - Bandar Tasek Mutiara,https://www.propertyguru.com.my/property-listi...,terrace
4,For Sale - Island Glades,https://www.propertyguru.com.my/property-listi...,terrace

In [162]:
property_df = pd.concat([condo_df, bungalow_df, semi_detached_df, terrace_df])

In [166]:
property_df.to_csv("property_data.csv", index=False)